name: Deploy SpeakReview

on:
  push:
    branches: [main]
    paths:
      - "site/**"
      - ".github/workflows/deploy.yml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Get the latest website file
        uses: actions/checkout@v7

      - name: Log in to AWS
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::651323680251:role/github-deploy-public-speaking-coach
          aws-region: us-east-1

      - name: Upload website files to S3
        run: aws s3 sync site/ s3://public-speaking-coach-jayvee-frontend/ --cache-control "no-cache"
